<?php
session_start();
require_once '../database/db_connect.php';

if (!isset($_SESSION['admin_id'])) {
    header('Location: admin_login.php');
    exit();
}

$type = $_GET['type'] ?? 'full_report';
$format = $_GET['format'] ?? 'csv';

// Set headers for CSV download
if ($format == 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="organic_marketplace_report_' . date('Y-m-d') . '.csv"');
    
    $output = fopen('php://output', 'w');
    
    // Add BOM for UTF-8 Excel compatibility
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
    
    switch ($type) {
        case 'category_sales':
            fputcsv($output, ['ORGANIC MARKETPLACE - CATEGORY SALES REPORT']);
            fputcsv($output, ['Generated: ' . date('Y-m-d H:i:s')]);
            fputcsv($output, ['Generated by: ' . $_SESSION['admin_username']]);
            fputcsv($output, []);
            fputcsv($output, ['Category', 'Product Count', 'Units Sold', 'Total Revenue (₱)', 'Average Price (₱)']);
            
            $category_sales = @$conn->query("
                SELECT 
                    p.category,
                    COUNT(DISTINCT p.id) as product_count,
                    COALESCE(SUM(p.sold), 0) as total_sold,
                    COALESCE(SUM(p.sold * p.price), 0) as total_revenue,
                    COALESCE(AVG(p.price), 0) as avg_price
                FROM products p
                GROUP BY p.category
                ORDER BY total_sold DESC
            ");
            
            $totalProducts = 0;
            $totalSold = 0;
            $totalRevenue = 0;
            $organic_crops = ['Vegetables', 'Fruits', 'Cacao', 'Spices'];
            $eggs_poultry = ['Eggs'];
            $fishery = ['Fish'];
            $organic_sold = 0;
            $organic_rev = 0;
            $eggs_sold = 0;
            $eggs_rev = 0;
            $fishery_sold = 0;
            $fishery_rev = 0;
            
            if ($category_sales && $category_sales->num_rows > 0) {
                while ($row = $category_sales->fetch_assoc()) {
                    fputcsv($output, [
                        $row['category'],
                        $row['product_count'],
                        $row['total_sold'],
                        number_format($row['total_revenue'], 2),
                        number_format($row['avg_price'], 2)
                    ]);
                    $totalProducts += $row['product_count'];
                    $totalSold += $row['total_sold'];
                    $totalRevenue += $row['total_revenue'];
                    
                    // Categorize for group summary
                    if (in_array($row['category'], $organic_crops)) {
                        $organic_sold += $row['total_sold'];
                        $organic_rev += $row['total_revenue'];
                    } elseif (in_array($row['category'], $eggs_poultry)) {
                        $eggs_sold += $row['total_sold'];
                        $eggs_rev += $row['total_revenue'];
                    } elseif (in_array($row['category'], $fishery)) {
                        $fishery_sold += $row['total_sold'];
                        $fishery_rev += $row['total_revenue'];
                    }
                }
                fputcsv($output, []);
                fputcsv($output, ['TOTAL', $totalProducts, $totalSold, number_format($totalRevenue, 2), '']);
                fputcsv($output, []);
                fputcsv($output, ['CATEGORY GROUP SUMMARY']);
                fputcsv($output, ['Category Group', 'Units Sold', 'Total Revenue (₱)']);
                fputcsv($output, ['Organic Crops (Vegetables, Fruits, Cacao, Spices)', $organic_sold, number_format($organic_rev, 2)]);
                fputcsv($output, ['Eggs/Poultry', $eggs_sold, number_format($eggs_rev, 2)]);
                fputcsv($output, ['Fishery (Fish)', $fishery_sold, number_format($fishery_rev, 2)]);
            } else {
                fputcsv($output, ['No category sales data available']);
            }
            break;
            
        case 'buyer_demographics':
            fputcsv($output, ['ORGANIC MARKETPLACE - BUYER DEMOGRAPHICS REPORT']);
            fputcsv($output, ['Generated: ' . date('Y-m-d H:i:s')]);
            fputcsv($output, ['Generated by: ' . $_SESSION['admin_username']]);
            fputcsv($output, []);
            
            // Total buyers
            $totalBuyersQ = @$conn->query("SELECT COUNT(*) as total FROM buyers");
            $totalBuyers = $totalBuyersQ ? $totalBuyersQ->fetch_assoc()['total'] : 0;
            fputcsv($output, ['Total Buyers', $totalBuyers]);
            fputcsv($output, []);
            
            // Check if barangay column exists
            $colCheck = @$conn->query("SHOW COLUMNS FROM buyers LIKE 'barangay'");
            if ($colCheck && $colCheck->num_rows > 0) {
                fputcsv($output, ['BARANGAY DISTRIBUTION']);
                fputcsv($output, ['Barangay', 'Buyer Count', 'Percentage']);
                
                // Barangay distribution
                $barangays = @$conn->query("
                    SELECT barangay, COUNT(*) as buyer_count
                    FROM buyers
                    WHERE barangay IS NOT NULL AND barangay != ''
                    GROUP BY barangay
                    ORDER BY buyer_count DESC
                ");
                
                if ($barangays && $barangays->num_rows > 0) {
                    while ($row = $barangays->fetch_assoc()) {
                        $percentage = $totalBuyers > 0 ? number_format(($row['buyer_count'] / $totalBuyers) * 100, 2) : 0;
                        fputcsv($output, [$row['barangay'], $row['buyer_count'], $percentage . '%']);
                    }
                } else {
                    fputcsv($output, ['No barangay data available']);
                }
                
                fputcsv($output, []); // Empty row
                fputcsv($output, ['AGE GROUP DISTRIBUTION']);
                fputcsv($output, ['Age Group', 'Count', 'Percentage']);
                
                $age_groups = @$conn->query("
                    SELECT age_group, COUNT(*) as count
                    FROM buyers
                    WHERE age_group IS NOT NULL AND age_group != ''
                    GROUP BY age_group
                    ORDER BY age_group
                ");
                
                if ($age_groups && $age_groups->num_rows > 0) {
                    $totalWithAge = 0;  
                    $ageData = [];
                    while ($row = $age_groups->fetch_assoc()) {
                        $ageData[] = $row;
                        $totalWithAge += $row['count'];
                    }
                    foreach ($ageData as $row) {
                        $percentage = $totalWithAge > 0 ? number_format(($row['count'] / $totalWithAge) * 100, 2) : 0;
                        fputcsv($output, [$row['age_group'], $row['count'], $percentage . '%']);
                    }
                } else {
                    fputcsv($output, ['No age group data available']);
                }
            } else {
                fputcsv($output, ['Demographics columns not available']);
                fputcsv($output, ['Run database migration to enable demographics tracking']);
            }
            break;
            
        case 'monthly_sales':
            fputcsv($output, ['ORGANIC MARKETPLACE - MONTHLY SALES REPORT']);
            fputcsv($output, ['Generated: ' . date('Y-m-d H:i:s')]);
            fputcsv($output, ['Generated by: ' . $_SESSION['admin_username']]);
            fputcsv($output, ['Period: Last 12 Months']);
            fputcsv($output, []);
            fputcsv($output, ['Month', 'Order Count', 'Total Revenue (₱)', 'Units Sold', 'Average Order Value (₱)']);
            
            $monthly_sales = @$conn->query("
                SELECT 
                    DATE_FORMAT(order_date, '%Y-%m') as month,
                    COUNT(*) as order_count,
                    COALESCE(SUM(total), 0) as total_revenue,
                    COALESCE(SUM(quantity), 0) as total_quantity
                FROM orders
                WHERE order_date >= DATE_SUB(NOW(), INTERVAL 12 MONTH)
                GROUP BY DATE_FORMAT(order_date, '%Y-%m')
                ORDER BY month DESC
            ");
            
            $totalRevenue = 0;
            $totalOrders = 0;
            $totalUnits = 0;
            
            if ($monthly_sales && $monthly_sales->num_rows > 0) {
                while ($row = $monthly_sales->fetch_assoc()) {
                    $avgOrderValue = $row['order_count'] > 0 ? ($row['total_revenue'] / $row['order_count']) : 0;
                    fputcsv($output, [
                        date('F Y', strtotime($row['month'] . '-01')),
                        $row['order_count'],
                        number_format($row['total_revenue'], 2),
                        $row['total_quantity'],
                        number_format($avgOrderValue, 2)
                    ]);
                    $totalRevenue += $row['total_revenue'];
                    $totalOrders += $row['order_count'];
                    $totalUnits += $row['total_quantity'];
                }
                fputcsv($output, []);
                fputcsv($output, ['TOTAL (12 Months)', $totalOrders, number_format($totalRevenue, 2), $totalUnits, number_format($totalOrders > 0 ? ($totalRevenue / $totalOrders) : 0, 2)]);
            } else {
                fputcsv($output, ['No monthly sales data available']);
            }
            break;
            
        case 'full_report':
        default:
            // Full comprehensive report
            fputcsv($output, ['ORGANIC MARKETPLACE - COMPREHENSIVE REPORT']);
            fputcsv($output, ['Generated: ' . date('Y-m-d H:i:s')]);
            fputcsv($output, ['Generated by: ' . $_SESSION['admin_username']]);
            fputcsv($output, []);
            
            // Summary Statistics
            fputcsv($output, ['SUMMARY STATISTICS']);
            
            $farmers_q = @$conn->query("SELECT COUNT(*) as c FROM farmers");
            $buyers_q = @$conn->query("SELECT COUNT(*) as c FROM buyers");
            $products_q = @$conn->query("SELECT COUNT(*) as c FROM products");
            $orders_q = @$conn->query("SELECT COUNT(*) as c FROM orders");
            $revenue_q = @$conn->query("SELECT COALESCE(SUM(total), 0) as s FROM orders");
            
            $stats = [
                ['Total Farmers', $farmers_q ? $farmers_q->fetch_assoc()['c'] : 0],
                ['Total Buyers', $buyers_q ? $buyers_q->fetch_assoc()['c'] : 0],
                ['Total Products', $products_q ? $products_q->fetch_assoc()['c'] : 0],
                ['Total Orders', $orders_q ? $orders_q->fetch_assoc()['c'] : 0],
                ['Total Revenue', '₱' . number_format($revenue_q ? $revenue_q->fetch_assoc()['s'] : 0, 2)]
            ];
            
            foreach ($stats as $stat) {
                fputcsv($output, $stat);
            }
            fputcsv($output, []);
            
            // Category Sales
            fputcsv($output, ['CATEGORY SALES']);
            fputcsv($output, ['Category', 'Product Count', 'Units Sold', 'Total Revenue (₱)', 'Average Price (₱)']);
            
            $category_sales_full = @$conn->query("
                SELECT 
                    p.category,
                    COUNT(DISTINCT p.id) as product_count,
                    COALESCE(SUM(p.sold), 0) as total_sold,
                    COALESCE(SUM(p.sold * p.price), 0) as total_revenue,
                    COALESCE(AVG(p.price), 0) as avg_price
                FROM products p
                GROUP BY p.category
                ORDER BY total_sold DESC
            ");
            
            if ($category_sales_full) {
                while ($row = $category_sales_full->fetch_assoc()) {
                    fputcsv($output, [
                        $row['category'],
                        $row['product_count'],
                        $row['total_sold'],
                        number_format($row['total_revenue'], 2),
                        number_format($row['avg_price'], 2)
                    ]);
                }
            }
            fputcsv($output, []);
            
            // Buyer Demographics
            fputcsv($output, ['BUYER DEMOGRAPHICS']);
            $colCheck = $conn->query("SHOW COLUMNS FROM buyers LIKE 'barangay'");
            if ($colCheck->num_rows > 0) {
                fputcsv($output, ['Barangay', 'Buyer Count']);
                
                $barangays = @$conn->query("
                    SELECT barangay, COUNT(*) as buyer_count
                    FROM buyers
                    WHERE barangay IS NOT NULL AND barangay != ''
                    GROUP BY barangay
                    ORDER BY buyer_count DESC
                ");
                
                if ($barangays) {
                    while ($row = $barangays->fetch_assoc()) {
                        fputcsv($output, [$row['barangay'], $row['buyer_count']]);
                    }
                }
            } else {
                $totalBuyers = @$conn->query("SELECT COUNT(*) as c FROM buyers");
                if ($totalBuyers) {
                    fputcsv($output, ['Total Buyers', $totalBuyers->fetch_assoc()['c']]);
                } else {
                    fputcsv($output, ['Total Buyers', '0']);
                }
            }
            fputcsv($output, []);
            
            // Monthly Sales
            fputcsv($output, ['MONTHLY SALES (Last 12 Months)']);
            fputcsv($output, ['Month', 'Order Count', 'Total Revenue (₱)', 'Units Sold', 'Average Order Value (₱)']);
            
            $monthly_sales_full = @$conn->query("
                SELECT 
                    DATE_FORMAT(order_date, '%Y-%m') as month,
                    COUNT(*) as order_count,
                    COALESCE(SUM(total), 0) as total_revenue,
                    COALESCE(SUM(quantity), 0) as total_quantity
                FROM orders
                WHERE order_date >= DATE_SUB(NOW(), INTERVAL 12 MONTH)
                GROUP BY DATE_FORMAT(order_date, '%Y-%m')
                ORDER BY month DESC
            ");
            
            $grandTotalRevenue = 0;
            $grandTotalOrders = 0;
            $grandTotalUnits = 0;
            
            if ($monthly_sales_full && $monthly_sales_full->num_rows > 0) {
                while ($row = $monthly_sales_full->fetch_assoc()) {
                    $avgOrderValue = $row['order_count'] > 0 ? ($row['total_revenue'] / $row['order_count']) : 0;
                    fputcsv($output, [
                        date('F Y', strtotime($row['month'] . '-01')),
                        $row['order_count'],
                        number_format($row['total_revenue'], 2),
                        $row['total_quantity'],
                        number_format($avgOrderValue, 2)
                    ]);
                    $grandTotalRevenue += $row['total_revenue'];
                    $grandTotalOrders += $row['order_count'];
                    $grandTotalUnits += $row['total_quantity'];
                }
                fputcsv($output, []);
                fputcsv($output, ['TOTAL (12 Months)', $grandTotalOrders, number_format($grandTotalRevenue, 2), $grandTotalUnits, number_format($grandTotalOrders > 0 ? ($grandTotalRevenue / $grandTotalOrders) : 0, 2)]);
            } else {
                fputcsv($output, ['No monthly sales data available']);
            }
            fputcsv($output, []);
            
            // Top Products
            fputcsv($output, ['TOP SELLING PRODUCTS']);
            fputcsv($output, ['Product Name', 'Category', 'Farmer', 'Units Sold', 'Total Revenue (₱)', 'Location']);
            
            $top_products = @$conn->query("
                SELECT 
                    p.name,
                    p.category,
                    f.name as farmer_name,
                    p.sold,
                    COALESCE(p.sold * p.price, 0) as revenue,
                    p.location
                FROM products p
                JOIN farmers f ON p.farmer_id = f.id
                WHERE p.sold > 0
                ORDER BY p.sold DESC
                LIMIT 20
            ");
            
            if ($top_products && $top_products->num_rows > 0) {
                while ($row = $top_products->fetch_assoc()) {
                    fputcsv($output, [
                        $row['name'],
                        $row['category'],
                        $row['farmer_name'],
                        $row['sold'],
                        number_format($row['revenue'], 2),
                        $row['location']
                    ]);
                }
            } else {
                fputcsv($output, ['No product sales data available']);
            }
            fputcsv($output, []);
            
            // Seller Statistics
            fputcsv($output, ['SELLER STATISTICS']);
            fputcsv($output, ['Seller Name', 'Email', 'Location', 'Products Listed', 'Total Units Sold', 'Total Revenue (₱)']);
            
            $seller_stats = @$conn->query("
                SELECT 
                    f.name,
                    f.email,
                    f.location,
                    COUNT(DISTINCT p.id) as products_count,
                    COALESCE(SUM(p.sold), 0) as total_sold,
                    COALESCE(SUM(p.sold * p.price), 0) as total_revenue
                FROM farmers f
                LEFT JOIN products p ON f.id = p.farmer_id
                GROUP BY f.id
                ORDER BY total_revenue DESC
            ");
            
            if ($seller_stats && $seller_stats->num_rows > 0) {
                while ($row = $seller_stats->fetch_assoc()) {
                    fputcsv($output, [
                        $row['name'],
                        $row['email'],
                        $row['location'],
                        $row['products_count'],
                        $row['total_sold'],
                        number_format($row['total_revenue'], 2)
                    ]);
                }
            } else {
                fputcsv($output, ['No seller statistics available']);
            }
            fputcsv($output, []);
            
            // Order Status Summary
            fputcsv($output, ['ORDER STATUS SUMMARY']);
            fputcsv($output, ['Status', 'Order Count', 'Total Revenue (₱)']);
            
            $order_status = @$conn->query("
                SELECT 
                    status,
                    COUNT(*) as order_count,
                    COALESCE(SUM(total), 0) as total_revenue
                FROM orders
                GROUP BY status
                ORDER BY order_count DESC
            ");
            
            if ($order_status && $order_status->num_rows > 0) {
                while ($row = $order_status->fetch_assoc()) {
                    fputcsv($output, [
                        $row['status'],
                        $row['order_count'],
                        number_format($row['total_revenue'], 2)
                    ]);
                }
            } else {
                fputcsv($output, ['No order status data available']);
            }
            fputcsv($output, []);
            
            // Category Group Summary
            fputcsv($output, ['CATEGORY GROUP SUMMARY']);
            fputcsv($output, ['Category Group', 'Units Sold', 'Total Revenue (₱)']);
            
            $organic_crops = ['Vegetables', 'Fruits', 'Cacao', 'Spices'];
            $eggs_poultry = ['Eggs'];
            $fishery = ['Fish'];
            
            $organic_sold = 0;
            $organic_rev = 0;
            $eggs_sold = 0;
            $eggs_rev = 0;
            $fishery_sold = 0;
            $fishery_rev = 0;
            
            if ($category_sales_full) {
                $category_sales_full->data_seek(0);
                while ($row = $category_sales_full->fetch_assoc()) {
                    if (in_array($row['category'], $organic_crops)) {
                        $organic_sold += $row['total_sold'];
                        $organic_rev += $row['total_revenue'];
                    } elseif (in_array($row['category'], $eggs_poultry)) {
                        $eggs_sold += $row['total_sold'];
                        $eggs_rev += $row['total_revenue'];
                    } elseif (in_array($row['category'], $fishery)) {
                        $fishery_sold += $row['total_sold'];
                        $fishery_rev += $row['total_revenue'];
                    }
                }
            }
            
            fputcsv($output, ['Organic Crops (Vegetables, Fruits, Cacao, Spices)', $organic_sold, number_format($organic_rev, 2)]);
            fputcsv($output, ['Eggs/Poultry', $eggs_sold, number_format($eggs_rev, 2)]);
            fputcsv($output, ['Fishery (Fish)', $fishery_sold, number_format($fishery_rev, 2)]);
            break;
            
        case 'order_details':
            fputcsv($output, ['ORGANIC MARKETPLACE - ORDER DETAILS REPORT']);
            fputcsv($output, ['Generated: ' . date('Y-m-d H:i:s')]);
            fputcsv($output, ['Generated by: ' . $_SESSION['admin_username']]);
            fputcsv($output, []);
            fputcsv($output, ['Order ID', 'Date', 'Buyer', 'Product', 'Category', 'Quantity', 'Unit Price (₱)', 'Total (₱)', 'Status', 'Location']);
            
            $orders = @$conn->query("
                SELECT 
                    o.id,
                    o.order_date,
                    b.name as buyer_name,
                    p.name as product_name,
                    p.category,
                    o.quantity,
                    o.price,
                    o.total,
                    o.status,
                    o.location
                FROM orders o
                JOIN buyers b ON o.buyer_id = b.id
                JOIN products p ON o.product_id = p.id
                ORDER BY o.order_date DESC
            ");
            
            $orderTotal = 0;
            $orderCount = 0;
            
            if ($orders && $orders->num_rows > 0) {
                while ($row = $orders->fetch_assoc()) {
                    fputcsv($output, [
                        $row['id'],
                        date('Y-m-d H:i', strtotime($row['order_date'])),
                        $row['buyer_name'],
                        $row['product_name'],
                        $row['category'],
                        $row['quantity'],
                        number_format($row['price'], 2),
                        number_format($row['total'], 2),
                        $row['status'],
                        $row['location']
                    ]);
                    $orderTotal += $row['total'];
                    $orderCount++;
                }
                fputcsv($output, []);
                fputcsv($output, ['TOTAL', '', '', '', '', '', '', number_format($orderTotal, 2), '', '']);
                fputcsv($output, ['Total Orders', $orderCount]);
            } else {
                fputcsv($output, ['No order data available']);
            }
            break;
            
        case 'product_inventory':
            fputcsv($output, ['ORGANIC MARKETPLACE - PRODUCT INVENTORY REPORT']);
            fputcsv($output, ['Generated: ' . date('Y-m-d H:i:s')]);
            fputcsv($output, ['Generated by: ' . $_SESSION['admin_username']]);
            fputcsv($output, []);
            fputcsv($output, ['Product ID', 'Product Name', 'Category', 'Farmer', 'Price (₱)', 'Available Quantity', 'Units Sold', 'Location', 'Status']);
            
            $products = @$conn->query("
                SELECT 
                    p.id,
                    p.name,
                    p.category,
                    f.name as farmer_name,
                    p.price,
                    p.quantity,
                    p.sold,
                    p.location,
                    CASE 
                        WHEN p.quantity = 0 THEN 'Out of Stock'
                        WHEN p.quantity < 10 THEN 'Low Stock'
                        ELSE 'In Stock'
                    END as status
                FROM products p
                JOIN farmers f ON p.farmer_id = f.id
                ORDER BY p.category, p.name
            ");
            
            if ($products && $products->num_rows > 0) {
                while ($row = $products->fetch_assoc()) {
                    fputcsv($output, [
                        $row['id'],
                        $row['name'],
                        $row['category'],
                        $row['farmer_name'],
                        number_format($row['price'], 2),
                        $row['quantity'],
                        $row['sold'],
                        $row['location'],
                        $row['status']
                    ]);
                }
            } else {
                fputcsv($output, ['No product data available']);
            }
            break;
            
        case 'seller_performance':
            fputcsv($output, ['ORGANIC MARKETPLACE - SELLER PERFORMANCE REPORT']);
            fputcsv($output, ['Generated: ' . date('Y-m-d H:i:s')]);
            fputcsv($output, ['Generated by: ' . $_SESSION['admin_username']]);
            fputcsv($output, []);
            fputcsv($output, ['Seller Name', 'Email', 'Location', 'Products Listed', 'Total Units Sold', 'Total Revenue (₱)', 'Average Product Price (₱)', 'Best Selling Product']);
            
            $sellers = @$conn->query("
                SELECT 
                    f.id,
                    f.name,
                    f.email,
                    f.location,
                    COUNT(DISTINCT p.id) as products_count,
                    COALESCE(SUM(p.sold), 0) as total_sold,
                    COALESCE(SUM(p.sold * p.price), 0) as total_revenue,
                    COALESCE(AVG(p.price), 0) as avg_price
                FROM farmers f
                LEFT JOIN products p ON f.id = p.farmer_id
                GROUP BY f.id
                ORDER BY total_revenue DESC
            ");
            
            if ($sellers && $sellers->num_rows > 0) {
                while ($seller = $sellers->fetch_assoc()) {
                    // Get best selling product for this seller
                    $bestProduct = @$conn->query("
                        SELECT name 
                        FROM products 
                        WHERE farmer_id = " . intval($seller['id']) . " 
                        AND sold > 0 
                        ORDER BY sold DESC 
                        LIMIT 1
                    ");
                    $bestProductName = 'None';
                    if ($bestProduct && $bestProduct->num_rows > 0) {
                        $bestProductName = $bestProduct->fetch_assoc()['name'];
                    }
                    
                    fputcsv($output, [
                        $seller['name'],
                        $seller['email'],
                        $seller['location'],
                        $seller['products_count'],
                        $seller['total_sold'],
                        number_format($seller['total_revenue'], 2),
                        number_format($seller['avg_price'], 2),
                        $bestProductName
                    ]);
                }
            } else {
                fputcsv($output, ['No seller data available']);
            }
            break;
    }
    
    fclose($output);
    exit();
} else {
    // For future PDF/Excel formats
    header('Location: analytics.php?error=format_not_supported');
    exit();
}
?>

